name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Build on Linux/macOS
      if: runner.os != 'Windows'
      run: |
        make

    - name: Build on Windows
      if: runner.os == 'Windows'
      run: |
        gcc -Wall -Wextra -O2 -c strap.c -o strap.o
        ar rcs libstrap.a strap.o

    - name: Run tests on Linux/macOS
      if: runner.os != 'Windows'
      run: |
        cd tests
        gcc -I.. -L.. -o test_strap test_strap.c -lstrap
        ./test_strap

    - name: Run tests on Windows
      if: runner.os == 'Windows'
      run: |
        cd tests
        gcc -I.. -L.. -o test_strap.exe test_strap.c -lstrap
        ./test_strap.exe