name: CI

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Build on Linux/macOS
      if: runner.os != 'Windows'
      run: |
        make

    - name: Configure on Windows
      if: runner.os == 'Windows'
      run: |
        cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DSTRAP_BUILD_TESTS=ON -DSTRAP_BUILD_BENCHMARKS=OFF -DCMAKE_BUILD_TYPE=Release

    - name: Build on Windows
      if: runner.os == 'Windows'
      run: |
        cmake --build build --config Release

    - name: Run tests on Linux/macOS
      if: runner.os != 'Windows'
      run: |
        cd tests
        gcc -I.. -L.. -o test_strap test_strap.c -lstrap
        ./test_strap

    - name: Run tests on Windows
      if: runner.os == 'Windows'
      run: |
        ctest --test-dir build --build-config Release --output-on-failure

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build release artifacts
        run: |
          make clean
          make

      - name: Package release artifacts
        run: |
          mkdir -p dist
          tar -czf dist/strap-${{ github.ref_name }}.tar.gz libstrap.a strap.h
          zip -j dist/strap-${{ github.ref_name }}.zip libstrap.a strap.h

      - name: Publish GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/strap-${{ github.ref_name }}.tar.gz
            dist/strap-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
